### ISSUE TITLE
[FEAT REQUEST] Add the Folder class

### ISSUE THREAD

**Issue by ccoeurderoy** [algoan/rest-nodejs#20]
### Description

The goal of this issue is to discuss the implementation of the Folder class. APIs to add:

- [`POST /folders/:id/legal-documents`](https://developers.algoan.com/api/#operation/postLegalDocuments)
- [`GET /folders/:id/legal-documents/:legalDocumentId`](https://developers.algoan.com/api/#operation/getLegalFile)
- [`POST /folders/:id/legal-documents/:legalDocumentId/files`](https://developers.algoan.com/api/#operation/postLegalFile)
- [`POST /folders/:id/signatures`](https://developers.algoan.com/api/#operation/createSignatureDocument)
- [`PATCH /folders/:id/signatures/:signatureId`](https://developers.algoan.com/api/#operation/getSignatureDocument)

_NOTE_: there are several ways to retrieve files and documents. For example, you could call `GET /folders/:folderId` which retrieves the entire folder, and then get files or documents.

_NOTE 2_: it needs to be retrieved from a Service Account

**Comment by amarlankri** [comment]
This is solution I think about:

1. Create a class `LegalDocument` which would implement an interface `ILegalDocument`. This class would keep a reference to parent folder `folderId: string` and would have these methods: 
```
// POST /folders/:id/legal-documents
static create(folderId: string, document: PostLegalDocument): Promise<LegalDocument> 

// GET /folders/:id/legal-documents/:legalDocumentId
static getById(folderId: string, legalDocumentId: string): Promise<LegalDocument>

// POST /folders/:id/legal-documents/:legalDocumentId/files
uploadFile(file: PostFileDTO): Promise<void> // no folderId argument since it is defined as property during construction
```

2. Create a class `Signature` which would implement an interface `ISignature`. This class would keep a reference to parent folder `folderId: string` and would have these methods:  
```
// POST /folders/:id/signatures
static create(folderId: string, signature: PostSignatureDTO): Promise<Signature>

// PATCH /folders/:id/signatures/:signatureId
update(signature: PathSignatureDTO): Promise<void> // no folderId argument since it is defined as property during construction
```

3. Create a class `Folder` which would  implement an interface `IFolder`. This class would have these methods (each one invoke a static method defined previously):
```
createLegalDocument(document: PostLegalDocument): Promise<LegalDocument>

getLegalDocumentById(documentId: string): Promise<LegalDocument>

createSignature(signature: PostSignatureDTO): Promise<Signature>
```

In addition, to get a folder instance, a static method would be created:
```
static getById(folderId: string): Promise<Folder>
```

4. Add the following method to `ServiceAccount` class. It would simply call `Folder.byId` method.
```
getFolderById(folderId: string): Promise<Folder>
```

------------

What do think @ccoeurderoy?

Maybe there are too many indirections (method which invoke static method) but it is a consequence of OOP style...

**Comment by ccoeurderoy** [comment]
Thank you @amarlankri! Well, I agree with most of your proposals. Just one detail you may not have noticed: `SupportingDocuments` and `LegalDocuments` are basically the same, except for the `category` which is different. So I suggest creating one `Document` class with a property set in the constructor indicating if it is a legal doc or not.

If it is, then all API calls will be filled with the `/legal-documents` path, otherwise, it will be `/supporting-documents`. Do you see what I mean?

To illustrate this, let's draw a UML diagram 🙂

**Comment by amarlankri** [comment]
> Thank you @amarlankri! Well, I agree with most of your proposals. Just one detail you may not have noticed: `SupportingDocuments` and `LegalDocuments` are basically the same, except for the `category` which is different. So I suggest creating one `Document` class with a property set in the constructor indicating if it is a legal doc or not.
> 
> If it is, then all API calls will be filled with the `/legal-documents` path, otherwise, it will be `/supporting-documents`. Do you see what I mean?

Yes, I do! You are right, it would be great to group together these types.

But since `category` are different for `SupportingDocument` and `LegalDocument` by type definition, we should create two different classes to have correct typing. Otherwise, `legalDocuments` and `supportingDocuments` properties from `Folder` would be both of type `Document[]` (except if we introduce casting according the boolean property you suggest). Am I wrong?

**Comment by ccoeurderoy** [comment]
> But since category are different for SupportingDocument and LegalDocument by type definition, we should create two different classes to have correct typing. Otherwise, legalDocuments and supportingDocuments properties from Folder would be both of type Document[] (except if we introduce casting according the boolean property you suggest). Am I wrong?

Yes you're right, we could something like:

```ts
class Document<T> {
  public id: string;
  // all other common property
  public category: T;
}

type LegalDocument = Document<LegalDocumentCategory>;
type SupportingDocument = Document<SupportingDocumentCategory>

// then
class Folder {
  public id: string;
  public legalDocuments: LegalDocument[];
  public supportingDocuments: SupportingDocument[];
}
```

where `LegalDocumentCategory` and `SupportingDocumentCategory` are enums

**Comment by amarlankri** [comment]
> Yes you're right, we could do something like:
> 
> ```ts
> class Document<T> {
>   public id: string;
>   // all other common property
>   public category: T;
> }
> 
> type LegalDocument = Document<LegalDocumentCategory>;
> type SupportingDocument = Document<SupportingDocumentCategory>
> 
> // then
> class Folder {
>   public id: string;
>   public legalDocuments: LegalDocument[];
>   public supportingDocuments: SupportingDocument[];
> }
> ```
> 
> where `LegalDocumentCategory` and `SupportingDocumentCategory` are enums

Good idea! But in that case, how do you change the route according if it is a legal document or a supporting document?

**Comment by ccoeurderoy** [comment]
> Good idea! But in that case, how do you change the route according if it is a legal document or a supporting document?

Since the document depends on the category, we could imagine in the Document constructor, something like:

```ts
constructor(...) {
  this.apiPath = this.category in LegalDocumentCategory ? 'legal-documents' : 'supporting-documents';
}
```

By the way, I've created a ts playground:

[Playground Link](https://www.typescriptlang.org/play?module=5#code/KYDwDg9gTgLgBAYwDYEMDOa4EEA8AVOUGYAOwBNMAhOAHzgGEA+OAbwFgAoObxCEtGFACuCGNAAUYIQCMkASwRw5ZAFxwBUOSQDmAGjhTZCxCmLboATzV4AlCwC+ne906dSQgLZxq7LjyxwALxwAORYIbqcPN5BoZQhTq4c7l70rFE89JF+3AAi2Y4cnDAWYMDYAcG4lIwA3MWl5VjUVThM9RwlZdhprSzKahpa2vaMScjomAAKKFCk8L7RCHwaImJQ4hnR3IbyigPqgsPZ2zy7xqhqWFgA2gC6J6cGMntwSNJXlPeP3DashYVOMt+PAwLESMAAO5wGZzEgwcQhACMETgNxYSlUoQATKiEKZgOYoFZvAA6AL2B5ojEHEIAZjxBKJJPopPolJstSAA)

**Comment by amarlankri** [comment]
> Since the document depends on the category, we could imagine in the Document constructor, something like:
> 
> ```ts
> constructor(...) {
>   this.apiPath = this.category in LegalDocumentCategory ? 'legal-documents' : 'supporting-documents';
> }
> ```


That is an idea but I have another proposition. It would be to make `Document` abstract like this:

```ts
abstract class Document<T> {
  public id: string;
  private readonly path: string;
  // all other common property
  public category: T;

  abstract getPathApi(): string;
}

class LegalDocument extends Document<LegalDocumentCategory> {
    getPathApi() { 
        return "/legal-documents"
    }
}

class SupportingDocument extends Document<SupportingDocumentCategory> {
    getPathApi() { 
        return "/supporting-documents"
    }
}

// then
class Folder {
  public id: string;
  public legalDocuments: LegalDocument[];
  public supportingDocuments: SupportingDocument[];
}
```
 
I think it would be more maintainable if other kind of document are created. What do you think @ccoeurderoy?

(See [this playground](https://www.typescriptlang.org/play?module=5#code/KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAEQkwFcBbYAOxgB4AVAPjgG8BYAKDl8VXRZ4Ac2AwACghgALAIJgAlgAoAlAC44aKAprCA3NwC+vbt1pU4AIXbc+cWXAC8cAOSyXAGlt9rzl5ZcjUy5zSjgAYRsePnCvaN5iOMNgvAIiABlgYQRcUgpqOjhQGFoAEyI8qloGS1ZOeLhRCSk5RVV2OG87XigxcigaOAAiAHpcLJyAWlKyKroUIa64ZK4V7lTCOABlcjBIWB1hSoL4YrKK2ZP6cLqlpskZeWUVDqW7Xph+wdGUXf2YQ7TS7VBZLFZrLhAA))

**Comment by ccoeurderoy** [comment]
Yes totally! We just need to avoid calling the `getPathApi` whenever we call an API, it could be set in the constructor, right?

**Comment by ccoeurderoy** [comment]
But in my opinion, with your proposition, no need to have a generic abstract class `Document`. So with your solution, it will become:

```ts
abstract class Document {
  public id: string;
  private readonly path: string;

  abstract getPathApi(): string;
}

class LegalDocument extends Document {
    category: LegalDocumentCategory
    getPathApi() { 
        return "/legal-documents"
    }
}

class SupportingDocument extends Document {
   category: SupportingDocumentCategory;
    getPathApi() { 
        return "/supporting-documents"
    }
}

// then
class Folder {
  public id: string;
  public legalDocuments: LegalDocument[];
  public supportingDocuments: SupportingDocument[];
}
```

**Comment by amarlankri** [comment]
> Yes totally! We just need to avoid calling the `getPathApi` whenever we call an API, it could be set in the constructor, right?

Yes, I was not sure we can do that with typescript. So, finally, it would look like:

```ts
abstract class Document<T> {
  public id: string;
  // all other common property
  public category: T;

  abstract readonly pathApi: string;
}

class LegalDocument extends Document<LegalDocumentCategory> {
    readonly pathApi: string;

    constructor() {
        super()
        this.pathApi = "/legal-documents"
    }
}

class SupportingDocument extends Document<SupportingDocumentCategory> {
    readonly pathApi: string;

    constructor() {
        super()
        this.pathApi = "/supporting-documents"
    }
}

// then
class Folder {
  public id: string;
  public legalDocuments: LegalDocument[];
  public supportingDocuments: SupportingDocument[];
}
```
[playground](https://www.typescriptlang.org/play?module=5#code/KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAEQkwFcBbYAOxgB4AVAPjgG8BYAKDl8VXRZ4UYAgAmEGrgCecMAhgALAIJgAlgC44aKGpoBzANzduAX14mutKnABC7bnzjK4AXjgByZR4A0jvvbuHrYeZpbWlHAAwg48fFF+cbzEiaaWeAREADLA+gi4pBTUdHCgMLRiRIVUtAy2rJxJcCLikjJyCirqWjp6RpZOmJI65NjQABQAlLFOTijkYMBQU-6zcEpqKAB08kqqam5wAEQA9Li5+QC0EkW1KEercGlcz9wZhHAAyguQsH3VxXgZQqVTINTo9CiDUeLQkUlkuy6mm06D6xi4jyGNBGY2W00aa1480WeMeTg220R+0Op2JvxgfWuYMB90erxeliAA)

Is it okay for you?

**Comment by amarlankri** [comment]
> But in my opinion, with your proposition, no need to have a generic abstract class `Document`. So with your solution, it will become:
> 
> ```ts
> abstract class Document {
>   public id: string;
>   private readonly path: string;
> 
>   abstract getPathApi(): string;
> }
> 
> class LegalDocument extends Document {
>     category: LegalDocumentCategory
>     getPathApi() { 
>         return "/legal-documents"
>     }
> }
> 
> class SupportingDocument extends Document {
>    category: SupportingDocumentCategory;
>     getPathApi() { 
>         return "/supporting-documents"
>     }
> }
> 
> // then
> class Folder {
>   public id: string;
>   public legalDocuments: LegalDocument[];
>   public supportingDocuments: SupportingDocument[];
> }
> ```

Exact!

**Comment by amarlankri** [comment]
Sorry I closed the issue by mistake.

**Comment by ccoeurderoy** [comment]
Ok let's do this 👍
